spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 또는 validate / none / create-drop 등
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: http://localhost:9200
#    index:
#      auto-create: false

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE
    co.elastic.clients.elasticsearch: TRACE
    org.elasticsearch.client: TRACE

